=== Guihrmsfo/rp2/lib/xml-security-bin-1_0_4/data/org/apache/xml/security/samples/output/voucher_uni.dtd
<!ENTITY % timedate " year   CDATA  #REQUIRED
                     month  (January | February | March | April | May | Juny | July | August | Sempember | October | November | December)  #REQUIRED
                     day    CDATA  #REQUIRED
                     hour   CDATA  #REQUIRED
                     minute CDATA  #REQUIRED
                     second CDATA  #REQUIRED">

<!ENTITY % yesno " value  (yes | no )  #REQUIRED">

<!ELEMENT Voucher  (Hotel , Customer , TransactionDetails )>

<!ELEMENT Hotel  (Name , Address , ElectronicContact )>

<!ELEMENT Customer  (Name , Address , ElectronicContact )>

<!ELEMENT Name  (#PCDATA | Person )*>

<!ELEMENT Person  (Title? , First+ , Middle? , Last )>

<!ELEMENT Title  (#PCDATA )>

<!ELEMENT First  (#PCDATA )>

<!ELEMENT Middle  (#PCDATA )>

<!ELEMENT Last  (#PCDATA )>

<!ELEMENT Address  (Number , Street , City , State? , Postcode , Country )>

<!ELEMENT ElectronicContact  (Telephone , FAX? , Email? )>

<!ELEMENT Number  (#PCDATA )>

<!ELEMENT Street  (#PCDATA )>

<!ELEMENT City  (#PCDATA )>

<!ELEMENT State  (#PCDATA )>

<!ELEMENT Postcode  (#PCDATA )>

<!ELEMENT Country  (#PCDATA )>

<!ELEMENT Telephone  (#PCDATA )>

<!ELEMENT FAX  (#PCDATA )>

<!ELEMENT Email  (#PCDATA )>

<!ELEMENT TransactionDetails  (VoucherNumber , HotelContact , DateTimeOfReservation , Rooms+ )>

<!ELEMENT VoucherNumber  (#PCDATA )>
<!ATTLIST VoucherNumber  priority  (high | medium | low )  #REQUIRED >

<!ELEMENT HotelContact  (#PCDATA | Person )*>

<!ELEMENT DateTimeOfReservation EMPTY>
<!ATTLIST DateTimeOfReservation  %timedate; >

<!ELEMENT Rooms  (TypeOfRoom , NumberOfRooms , TimeOfArrival , TimeOfDeparture , Breakfast , Lunch , Dinner , Price )>

<!ELEMENT TypeOfRoom EMPTY>
<!ATTLIST TypeOfRoom  type  (suite | bungalow | single | double )  #REQUIRED >

<!ELEMENT NumberOfRooms  (#PCDATA )>

<!ELEMENT TimeOfArrival EMPTY>
<!ATTLIST TimeOfArrival  %timedate; >
<!ELEMENT TimeOfDeparture EMPTY>
<!ATTLIST TimeOfDeparture  %timedate; >

<!ELEMENT Breakfast EMPTY>
<!ATTLIST Breakfast %yesno; >
<!ELEMENT Lunch EMPTY>
<!ATTLIST Lunch %yesno; >
<!ELEMENT Dinner EMPTY>
<!ATTLIST Dinner %yesno; >

<!ELEMENT Price  (#PCDATA )>
<!ATTLIST Price  currency CDATA  #REQUIRED >

=== Guihrmsfo/rp2/lib/xml-security-bin-1_0_4/data/org/apache/xml/security/samples/output/voucher_uni.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Voucher PUBLIC "-//WebSig Consortium//DTD Voucher v1.0 20000405//EN" "voucher_uni.dtd">
<Voucher xmlns="http://www.nue.et-inf.uni-siegen.de/websig/">
	<Hotel xmlns="">
		<Name>Imaginary London Hotel</Name>
		<Address>
			<Number>102</Number>
			<Street>Euston St.</Street>
			<City>London</City>
			<Postcode>12BJ s 1</Postcode>
			<Country>England</Country>
		</Address>
		<ElectronicContact>
			<Telephone>00447234556789</Telephone>
			<FAX>00447234556780</FAX>
			<Email>info@imaginaryhl.com</Email>
		</ElectronicContact>
	</Hotel>
	<Customer xmlns="">
		<Name>
			<Person>
				<Title>Mr.</Title>
				<First>John</First>
				<Last>Doe</Last>
			</Person>
		</Name>
		<Address>
			<Number>12</Number>
			<Street>Wall St.</Street>
			<City>New York</City>
			<Postcode>10023</Postcode>
			<Country>USA</Country>
		</Address>
		<ElectronicContact>
			<Telephone>+1(202)234-5678</Telephone>
			<Email>info@myisp.com</Email>
		</ElectronicContact>
	</Customer>
	<TransactionDetails xmlns="">
		<VoucherNumber priority="high">7890gfd</VoucherNumber>
		<HotelContact>
			<Person>
				<Title>Ms.</Title>
				<First>Annie</First>
				<Middle>H.</Middle>
				<Last>Brewer</Last>
			</Person>
		</HotelContact>
		<DateTimeOfReservation year="1999" month="March" day="173" hour="23" minute="20" second="00" />
		<Rooms>
			<TypeOfRoom type="suite" />
			<NumberOfRooms>1</NumberOfRooms>
			<TimeOfArrival year="1999" month="January" day="12" hour="12" minute="00" second="00" />
			<TimeOfDeparture year="1999" month="February" day="12" hour="12" minute="00" second="00" />
			<Breakfast value="yes" />
			<Lunch value="no" />
			<Dinner value="no" />
			<Price currency="USD">1000</Price>
		</Rooms>
		<Rooms>
			<TypeOfRoom type="single" />
			<NumberOfRooms>2</NumberOfRooms>
			<TimeOfArrival year="1999" month="January" day="12" hour="12" minute="00" second="00" />
			<TimeOfDeparture year="1999" month="February" day="12" hour="12" minute="00" second="00" />
			<Breakfast value="yes" />
			<Lunch value="no" />
			<Dinner value="no" />
			<Price currency="USD">1000</Price>
		</Rooms>
	</TransactionDetails>
</Voucher>
